
# Environment variables required for this build (do NOT change)
# -------------------------------------------------------------
ENV FMW_PKG=fmw_14.1.1.0.0_wls_lite_Disk1_1of1.zip \
    FMW_JAR=fmw_14.1.1.0.0_wls_lite_generic.jar

# Copy packages
# -------------
COPY --chown=oracle:root $FMW_PKG install.file oraInst.loc /u01/



CMD ["/tmp/start_sleep.sh"]
